// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwubrzqtcahbwnztjtcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3dWJyenF0Y2FoYnduenRqdGNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMzg2MjksImV4cCI6MjA2NjYxNDYyOX0.Bf169PM5SqZaoqcSrAyS5MpiESR-7rqeJoNp-kPx5gg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);